---
#Setup docker

- name: Install docker - arch
  pacman:
    name: "{{ docker_dependencies_arch_arm|default('') }}"
    state: latest
    force: yes
  notify: Restart docker

- name: Start docker
  service:
    name: docker
    state: started
    enabled: yes
